### PR TITLE
Add Integration Tests

### PR DESCRIPTION
**Pull request by samba2**
This rather large pull requests introduces integration tests.

The idea is as follows:
As file system events can be tricky and are not fully deterministic in a test setup, file system events are pre-recorded and stored as csv file. This is the task of `FileSystemEventRecords` which as standalone .NET console application.

Under production conditions, FileWatcherEx reacts on events emitted by the native FileSystemWatcher class. For the test, this event source is replaceable with the `ReplayFileSystemWatcherWrapper.cs`. In the unit test, the file system events are replayed as follows:

````c#
        _fileWatcher.Start();
        _replayer.Replay(@"scenario\create_file.csv");
        _fileWatcher.Stop();
````

For the detailed test setup see class `FileWatcherExIntegrationTest` . 

Having this test setup available I started to record scenarios using the `FileSystemEventRecords` and then replaying them via `FileWatcherEx`. See `scenario/README.md` for a detailed description.

The general idea is to have (after more refactoring) very little of those tests around. Instead, there should be more simple unit tests. However, usually there is no way around integration testing. Also, I found the scenario approach useful since they currently cover real-world scenarios.

The current coverage looks like this:
image

TODO: I stopped when I tried to test the subdirectory support. Here, 2 file system calls would need to be made replacable. See the comments on test case `CreateFileInsideSymbolicLinkDirectory` in `FileWatcherExIntegrationTest`  for more details.

Caveat: To make the native `FileSystemWatcher` injectable and replaceable (it does not have an accompanying interface), I introduced `FileSystemWatcherWrapper.cs` which provides the interface `IFileSystemWatcherWrapper` containing all the needed methods. The file also provides a low friction production implementation `FileSystemWatcherWrapper` by inheriting from the native `FileSystemWatcher` and implementing the new interface `IFileSystemWatcherWrapper` at the same time.

What is your general thought on that ? Again, we'd like to have some safety in the lib which best comes from reproducible (and understandable) automated tests.

### CODE REVIEW

**Comment by d2phap** [comment]
Thanks @samba2 
It looks good to me. You're welcome to do the refactoring and testing

**Comment by samba2** [comment]
I am glad you like it! I will continue to improve coverage for `MakeWatcher_Created` and `MakeWatcher_Deleted`. Once the code has a ~ 90 % coverage (definitely achievable) I will then enter the fun part: refactoring, simplification and eventually also reducing the amount of integration test again.

**Comment by samba2** [comment]
coverage is now at 88 %:
image

Still there are no logic changes (at least there should not be). Instead I've used a mix of "internal" access modifiers and additional indirections via Lambdas to set the code under test. So complexity of the prod code slightly increased but otherwise I would not have been able to retro-fit the tests.

Planning to do the prod code refactoring next.

**Review by d2phap — APPROVED** [review]
LGTM!

**Comment by d2phap** [comment]
I wait for the next code refactoring then I will publish new version

**Comment by samba2** [comment]
That is a good idea. Let's see how the week goes.

**Pull request merged**
